name: 'olist'
version: '1.0.0'
profile: 'olist'          # -> must match the top-level key in profiles.yml

model-paths: ["models"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
test-paths: ["tests"]
analysis-paths: ["analyses"]

target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  olist:
    staging:
      +materialized: view
    intermediate:
      +materialized: view
    marts:
      +materialized: table